### ISSUE TITLE
[Bug]: Error in Laravel Extension (WSL2 Windows)

### ISSUE THREAD

**Issue by HassanZahirnia** [laravel/vs-code-extension#10]
### Extension Version

0.1.11

### PHP Binary

Other

### Operating System

Linux

### What happened?

The extension fails to start on my machine. I use WSL2 (Ubuntu) within my Windows 11 machine.

![image](https://github.com/user-attachments/assets/c24e7c77-05a6-43d5-9db3-a2eb697e81f9)

Here are some errors logged:

```
[error] /bin/sh: 1: /home/hajx/.vscode-server/data/User/globalStorage/laravel.vscode-laravel/file-downloader-downloads/php-parser-0.1.6: Exec format error
[error] Error:
 Translation namespaces
 [error] /usr/bin/php -r "
define('LARAVEL_START', microtime(true));

```

**Comment by wsamoht** [comment]
I am getting this too on Linux Mint

```
[error] /bin/sh: 1: /home/****/.config/Code/User/globalStorage/laravel.vscode-laravel/file-downloader-downloads/php-parser-0.1.6: Exec format error
```

**Comment by cognitus** [comment]
I'm getting too in fedora

```bash
[error] /bin/sh: line 1: /home/****/.config/Code/User/globalStorage/laravel.vscode-laravel/file-downloader-downloads/php-parser-0.1.6: cannot execute binary file: Exec format error
```

**Comment by SamuelNitsche** [comment]
Well, looks like the internally used `php-parser` is arm64 only :(

```
❯ file php-parser-0.1.6
php-parser-0.1.6: Mach-O 64-bit arm64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|PIE>
```

**Comment by MaelBriantin** [comment]
It would be a good idea to mention “macos arm only” if the extension is only designed for this platform. This would be a first for VSCode extensions. An oversight perhaps?

**Comment by SamuelNitsche** [comment]
I created a workflow to build the binaries for macos (arm64 and x86) as well as linux x86.
https://github.com/SamuelNitsche/vs-code-php-parser-cli/blob/main/.github/workflows/build-release-binaries.yml

You can download the files from the release (https://github.com/SamuelNitsche/vs-code-php-parser-cli/releases/tag/0.1.9) and replace the file located at `~/.vscode-server/data/User/globalStorage/laravel.vscode-laravel/file-downloader-downloads`

**Comment by vincentauger** [comment]
> I created a workflow to build the binaries for macos (arm64 and x86) as well as linux x86. https://github.com/SamuelNitsche/vs-code-php-parser-cli/blob/main/.github/workflows/build-release-binaries.yml
> 
> You can download the files from the release (https://github.com/SamuelNitsche/vs-code-php-parser-cli/releases/tag/0.1.9) and replace the file located at `~/.vscode-server/data/User/globalStorage/laravel.vscode-laravel/file-downloader-downloads`

Thanks! 🔥 That worked for me.

```
❯ ./php-parser-0.1.6

  VS Code PHP Parser  0.1.6

  USAGE:  <command> [options] [arguments]

  autocomplete Parse the given PHP code and return the autocomplete results
  detect       Detect things we care about in the current code
```

**Comment by Tjaitil** [comment]
> I created a workflow to build the binaries for macos (arm64 and x86) as well as linux x86. https://github.com/SamuelNitsche/vs-code-php-parser-cli/blob/main/.github/workflows/build-release-binaries.yml
> 
> You can download the files from the release (https://github.com/SamuelNitsche/vs-code-php-parser-cli/releases/tag/0.1.9) and replace the file located at `~/.vscode-server/data/User/globalStorage/laravel.vscode-laravel/file-downloader-downloads`

I'm getting a permission denied issue in vscode in plugin. Anyway quick fix to solve that? I'm using mac x86_64

**Comment by cognitus** [comment]
> > I created a workflow to build the binaries for macos (arm64 and x86) as well as linux x86. https://github.com/SamuelNitsche/vs-code-php-parser-cli/blob/main/.github/workflows/build-release-binaries.yml
> > You can download the files from the release (https://github.com/SamuelNitsche/vs-code-php-parser-cli/releases/tag/0.1.9) and replace the file located at `~/.vscode-server/data/User/globalStorage/laravel.vscode-laravel/file-downloader-downloads`
> 
> I'm getting a permission denied issue in vscode in plugin. Anyway quick fix to solve that? I'm using mac x86_64

chmod +x <filename>

**Comment by IvanAquino** [comment]
I'm using zorin os on Intel i7 my solution was download the file https://github.com/SamuelNitsche/vs-code-php-parser-cli/releases/tag/0.1.9
```sh
mv php-parser-0.1.9-x86_64-linux php-parser-0.1.6
chmod +x php-parser-0.1.6
```

**Comment by lcdss** [comment]
After installing the `php-parser` built for `Linux` it stopped the error, but no autocomplete works. It always stuck `Loading...` indefinitely.

**Comment by eznix86** [comment]
> I'm using zorin os on Intel i7 my solution was download the file for linux from https://github.com/SamuelNitsche/vs-code-php-parser-cli/releases/tag/0.1.9
> 
> ```shell
> mv php-parser-0.1.9-x86_64-linux php-parser-0.1.6
> chmod +x php-parser-0.1.6
> ```

One liner, change directory to where it is crashing: then do

```
wget "https://github.com/SamuelNitsche/vs-code-php-parser-cli/releases/download/0.1.9/php-parser-0.1.9-$(uname -m)-$(uname -s)" -O php-parser-0.1.6 && chmod +x php-parser-0.1.6
```

Note: temporary fix

**Comment by DanielHemmati** [comment]
i am using ubuntu i am also seeing the same error for `php-parser-0.1.6`. 
this solution works though:

> You can download the files from the release (https://github.com/SamuelNitsche/vs-code-php-parser-cli/releases/tag/0.1.9) and replace the file located at ~/.vscode-server/data/User/globalStorage/laravel.vscode-laravel/file-downloader-downloads

but i won't go that way for now

**Comment by njosh13** [comment]
> I created a workflow to build the binaries for macos (arm64 and x86) as well as linux x86. https://github.com/SamuelNitsche/vs-code-php-parser-cli/blob/main/.github/workflows/build-release-binaries.yml
> 
> You can download the files from the release (https://github.com/SamuelNitsche/vs-code-php-parser-cli/releases/tag/0.1.9) and replace the file located at `~/.vscode-server/data/User/globalStorage/laravel.vscode-laravel/file-downloader-downloads`

worked for me too thanks.

**Comment by erickcomp** [comment]
> I created a workflow to build the binaries for macos (arm64 and x86) as well as linux x86. https://github.com/SamuelNitsche/vs-code-php-parser-cli/blob/main/.github/workflows/build-release-binaries.yml
> 
> You can download the files from the release (https://github.com/SamuelNitsche/vs-code-php-parser-cli/releases/tag/0.1.9) and replace the file located at `~/.vscode-server/data/User/globalStorage/laravel.vscode-laravel/file-downloader-downloads`

Thank you sir!

**Comment by binaryfire** [comment]
> i am using ubuntu i am also seeing the same error for `php-parser-0.1.6`. this solution works though:
> 
> > You can download the files from the release (https://github.com/SamuelNitsche/vs-code-php-parser-cli/releases/tag/0.1.9) and replace the file located at ~/.vscode-server/data/User/globalStorage/laravel.vscode-laravel/file-downloader-downloads
> 
> but i won't go that way for now

I'm running VS Code on Windows and using the [Remote Development](https://code.visualstudio.com/docs/remote/remote-overview) extension to connect to an Ubuntu 22.04 VM. Manually downloading `php-parser` stopped the `php-parser` errors but unfortunately the extension still crashes for me.

**Comment by TraLeeee** [comment]
I got this error on Arch Linux, the problem is i mainly use Docker to run PHP app and there's no PHP binary executable on my local machine. So the extensions just throw the exception:

```
2024-12-17 10:26:14.403 [info] Activating Laravel Extension...
2024-12-17 10:26:14.403 [info] Started
2024-12-17 10:26:14.471 [error] /usr/bin/env: ‘php’: No such file or directory
```

Any solution for this?

**Comment by asivaneswaran** [comment]
I am running Vs Code on Mac and I am getting this error as well:

```

$app->register(new VsCodeLaravel($app));
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

echo '__VSCODE_LARAVEL_START_OUTPUT__';
 function vsCodeTranslationValue($key, $value, $file, $lines): array {     $lineNumber = 1;     $keys = explode('.', $key);     $index = 0;     $currentKey = array_shift($keys);      while ($currentKey !== null && $index < count($lines)) {         $line = $lines[$index][1];          if (strpos($line, '"' . $currentKey . '"', 0) !== false || strpos($line, "'" . $currentKey . "'", 0) !== false) {             $lineNumber = $lines[$index][0];             $currentKey = array_shift($keys);         }          $index++;     }      return [         'value' => $value,         'path' => realpath($file),         'line' => $lineNumber,         'params' => preg_match_all('/\:([A-Za-z0-9_]+)/', $value, $matches) ? $matches[1] : [],     ]; }  function vscodeCollectTranslations(string $path, string $namespace = null) {     return collect(glob("{$path}/**/*.{php,json}", GLOB_BRACE))->map(function ($file) use ($path, $namespace) {         $key = pathinfo($file, PATHINFO_FILENAME);          if ($namespace) {             $key = "{$namespace}::{$key}";         }          $lang = collect(explode('/', str_replace($path, '', $file)))->filter()->first();          $fileLines = explode(PHP_EOL, file_get_contents($file));         $lines = [];         $inComment = false;          foreach ($fileLines as $index => $line) {             $trimmed = trim($line);              if (substr($trimmed, 0, 2) === '/*') {                 $inComment = true;                 continue;             }              if ($inComment) {                 if (substr($trimmed, -2) !== '*/') {                     continue;                 }                  $inComment = false;             }              if (substr($trimmed, 0, 2) === '//') {                 continue;             }              $lines[] = [$index + 1, $trimmed];         }          return [             'key' => $key,             'lang' => $lang,             'values' => collect(\Illuminate\Support\Arr::dot(__($key, [], $lang)))->map(function ($value, $key) use ($file, $lines) {                 if (is_array($value)) {                     return null;                 }                  return vsCodeTranslationValue($key, $value, $file, $lines);             })->filter(),         ];     }); }  $loader = app("translator")->getLoader(); $namespaces = $loader->namespaces();  $reflection = new ReflectionClass($loader); $property = $reflection->hasProperty("paths")   ? $reflection->getProperty("paths")   : $reflection->getProperty("path"); $property->setAccessible(true);  $paths = \Illuminate\Support\Arr::wrap($property->getValue($loader));  $default = collect($paths)->flatMap(function ($path) {   return vscodeCollectTranslations($path); });  $namespaced = collect($namespaces)->flatMap(function ($path, $namespace) {     return vscodeCollectTranslations($path, $namespace); });  $final = [];  foreach ($default->merge($namespaced) as $value) {     foreach ($value['values'] as $key => $v) {         $dotKey = "{$value['key']}.{$key}";          if (!isset($final[$dotKey])) {             $final[$dotKey] = [];         }          $final[$dotKey][$value['lang']] = $v;          if ($value['lang'] === \Illuminate\Support\Facades\App::currentLocale()) {             $final[$dotKey]['default'] = $v;         }     } }  echo json_encode($final); ;
echo '__VSCODE_LARAVEL_END_OUTPUT__';

exit(0);

```

**Comment by lcdss** [comment]
> I got this error on Arch Linux, the problem is i mainly use Docker to run PHP app and there's no PHP binary executable on my local machine. So the extensions just throw the exception:
> 
> ```
> 2024-12-17 10:26:14.403 [info] Activating Laravel Extension...
> 2024-12-17 10:26:14.403 [info] Started
> 2024-12-17 10:26:14.471 [error] /usr/bin/env: ‘php’: No such file or directory
> ```
> 
> Any solution for this?

I recommend you to have the php cli available in the host as many tools you may use rely on it. You can install it using `asdf` using the command: `PHP_WITHOUT_PEAR=yes PHP_CONFIGURE_OPTIONS="--with-password-argon2 --with-openssl --with-readline" asdf install php 8.4.1`

**Comment by jithincubet** [comment]
I too get this error

**Comment by BassemN** [comment]
I am facing the same issue. I’m using Ubuntu.

**Comment by raja-muhammad-asher** [comment]
I got this error on ubuntu linux

**Comment by devSviat** [comment]
The same error "/bin/sh: 1: /home/user/.vscode-server/data/User/globalStorage/laravel.vscode-laravel/file-downloader-downloads/php-parser-0.1.6: Exec format error" on Windows WSL, VS Code Version: 1.96.0

**Comment by aphrxia** [comment]
> I created a workflow to build the binaries for macos (arm64 and x86) as well as linux x86. https://github.com/SamuelNitsche/vs-code-php-parser-cli/blob/main/.github/workflows/build-release-binaries.yml
> 
> You can download the files from the release (https://github.com/SamuelNitsche/vs-code-php-parser-cli/releases/tag/0.1.9) and replace the file located at `~/.vscode-server/data/User/globalStorage/laravel.vscode-laravel/file-downloader-downloads`

Thanks. Working for me (VSCodium 1.96.0, on Debian 12)

**Comment by maverik23** [comment]
same

**Comment by shane-smith** [comment]
I am also receiving this error, WSL2 on Windows.

**Host:** Windows 10 Pro - 22H2 - build 19045.5247
**WSL2:** Ubuntu 20.04.6 LTS

`~/.vscode-server/data/User/globalStorage/laravel.vscode-laravel/file-downloader-downloads/php-parser-0.1.6`

**Comment by joetannenbaum** [comment]
Still working on Windows, but there are new binary builds in 0.1.12, just released. Please let me know if it helps Mac/Linux users.

**Comment by wsamoht** [comment]
Working here now on Linux Mint!!!! Thank you for the awesome plugin and the quick fix!

**Comment by maverik23** [comment]
> Still working on Windows, but there are new binary builds in 0.1.12, just released. Please let me know if it helps Mac/Linux users.

looks like it work, but now i have this error:


2024-12-17 14:05:32.916 [error] /bin/sh: -c: line 2829: unexpected EOF while looking for matching ``'
/bin/sh: -c: line 4505: syntax error: unexpected end of file


MacOS

**Comment by Tjaitil** [comment]
v.0.1.12 works on mac x86_64!

**Comment by cognitus** [comment]
working on fedora

**Comment by njosh13** [comment]
![image](https://github.com/user-attachments/assets/1c03c185-1266-4ba7-bdd7-1b79aadc7555)

This is the new error I get after installing the new update.

**Comment by Thomas-Emad** [comment]
> Still working on Windows, but there are new binary builds in 0.1.12, just released. Please let me know if it helps Mac/Linux users.

The error message is changed to be:
`
2024-12-18 10:41:22.420 [info] Activating Laravel Extension...
2024-12-18 10:41:22.420 [info] Started
2024-12-18 10:41:28.680 [error] 
2024-12-18 10:41:28.680 [error] 
2024-12-18 10:41:28.698 [error] 
2024-12-18 10:41:28.699 [error] 
2024-12-18 10:41:28.699 [error] 
2024-12-18 10:41:28.699 [error] 
`
I use Linux distribution Lubuntu 24.04

**Comment by alohstan** [comment]
working now as well. cool

**Comment by kevinbowie** [comment]
I think mine is solved now, but now I have another error 😕

**Comment by kevinbowie** [comment]
> I think mine is solved now, but now I have another error 😕 something like Translation namespaces

After having some brute force testing remove some files, I think I found the issue.
I think it is because the lang files contain too long characters and reach over limit?

**Comment by HassanZahirnia** [comment]
Just re-tried the extension with the new `0.1.13` update and now the problem is fixed! 🤩

![image](https://github.com/user-attachments/assets/1f472daf-c7f8-4f86-b785-3cebb8804c96)

Thank you @joetannenbaum! 🥰🙏
