### ISSUE TITLE
[Bug]: Extension not working giving error

### ISSUE THREAD

**Issue by hussain4real** [laravel/vs-code-extension#91]
### Extension Version

0.1.12

### PHP Binary

Valet

### Operating System

macOS

### What happened?

```shell
2024-12-19 11:48:16.364 [info] Stopped
2024-12-19 11:48:22.565 [info] Activating Laravel Extension...
2024-12-19 11:48:22.565 [info] Started
2024-12-19 11:48:30.708 [error] /bin/sh: /Users/amisha/Library/Application Support/Code: is a directory
```

**Comment by joetannenbaum** [comment]
We just released v0.1.13, can you verify that this is still an issue after upgrading?

**Comment by hussain4real** [comment]
when i update, it tried downloading binary but failed:

<img width="449" alt="image" src="https://github.com/user-attachments/assets/33a4fe84-130c-4d81-ab0d-dfbb37475606" />

**Comment by hussain4real** [comment]
I'm Macbook M1

**Comment by hussain4real** [comment]
and the error persist
<img width="824" alt="image" src="https://github.com/user-attachments/assets/b752cb96-5374-4e3e-a8eb-a79296854b87" />

**Comment by hussain4real** [comment]
Issue fixed, was using vscode insider, had uninstall and install vscode.
