### ISSUE TITLE
[Bug]: Failed to download binary for Laravel extension: php-parser-v0.1.34-arm64-linux

### ISSUE THREAD

**Issue by mikebronner** [laravel/vs-code-extension#94]
### Extension Version

0.1.13

### PHP Binary

Docker

### Operating System

macOS

### What happened?

Getting the following error after updating now:

```
Failed to download binary for Laravel extension: php-parser-v0.1.34-arm64-linux
```

**Comment by joetannenbaum** [comment]
Ah man, ok. Let me track down a linux arm64 GitHub Actions runner and I'll get this up for you. Sorry about that.

**Comment by joetannenbaum** [comment]
@mikebronner just added a binary to v0.1.34, hopefully it works for you 🤞 

Didn't want to leave you hanging before I head out on vacation, keep me posted.

**Comment by mikebronner** [comment]
@joetannenbaum thank you very much, enjoy your Christmas! I am not getting an error at this time. I'll report back in more detail tomorrow morning if anything comes up. Closing this for now.
